import { initAdvisor } from './advisor';
import { initCountdowns } from './countdown';
import { initExamTimers } from './exam-timer';
import { initForms } from './forms';
import { initMenus } from './menu';
import { initMotion } from './motion';
import { initPwa } from './pwa';
import { initQuickConvert } from './quick-convert';
import { initReading } from './reading';
import { initSearch } from './search';
import { initTheme } from './theme';
import { initToolMemory } from './tool-memory';

initTheme();
initCountdowns();
initExamTimers();
initMenus();
initForms();
initAdvisor();
initSearch();
initReading();
initQuickConvert();
initPwa();
initToolMemory();
initMotion();
